management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
spring.sleuth.sampler.probability=1.0
spring.zipkin.base-url=${ZIPKIN_URL:http://zipkin:9411}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name},trace=%X{traceId:-},span=%X{spanId:-}] %logger{36} - %msg%n
